# Generated by Django 5.1.7 on 2025-03-31 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('mobile', models.TextField()),
                ('name', models.TextField()),
                ('qualification', models.TextField()),
                ('gender', models.TextField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('experience', models.TextField()),
                ('agegroup', models.TextField()),
                ('speciality', models.TextField()),
            ],
            options={
                'db_table': 'tblDoctor',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('info', models.TextField()),
                ('child', models.TextField()),
                ('adult', models.TextField()),
                ('women', models.TextField()),
                ('banned', models.TextField()),
                ('why', models.TextField()),
            ],
            options={
                'db_table': 'tblDrug',
            },
        ),
        migrations.CreateModel(
            name='DrugDoctor',
            fields=[
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.drug')),
            ],
            options={
                'db_table': 'tblDrugDoctor',
            },
        ),
    ]
